KERNEL_CONFIG := kernel/.config
TARGET_PREBUILT_KERNEL := kernel/arch/arm/boot/Image

$(TARGET_PREBUILT_KERNEL) : $(KERNEL_CONFIG)
	$(MAKE) -C kernel ARM=arm CROSS_COMPILE=arm-eabi- kernel.img

$(KERNEL_CONFIG) :
	$(MAKE) -C kernel ARM=arm CROSS_COMPILE=arm-eabi- $(KERNEL_DEFCONFIG)

.PHONY : $(KERNEL_CONFIG) $(TARGET_PREBUILT_KERNEL)
